# Generated by Django 3.2 on 2025-02-05 19:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='code must be ISO 4217', regex='^[A-Z]{3}$')], verbose_name='code ISO 4217')),
                ('number', models.CharField(max_length=3, unique=True, validators=[django.core.validators.RegexValidator(message='code must be ISO 4217 numeric', regex='^[0-9]{3}$')], verbose_name='code ISO 4217 numeric')),
                ('name', models.CharField(max_length=32)),
                ('symbol', models.CharField(blank=True, max_length=16)),
                ('major_unit_name', models.CharField(max_length=32)),
                ('minor_unit', models.JSONField()),
            ],
            options={
                'verbose_name': 'currency',
                'verbose_name_plural': 'currencies',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.ForeignKey(default='USD', on_delete=django.db.models.deletion.PROTECT, related_name='wallets', to='wallet.currency')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('code', models.CharField(blank=True, max_length=255, unique=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Paid'), (3, 'Failed')], default=1)),
                ('paid_date', models.DateTimeField(blank=True, null=True)),
                ('currency', models.ForeignKey(default='USD', on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='wallet.currency', verbose_name='currency')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
